### ISSUE TITLE
Sort expenses by date

### ISSUE THREAD

**Issue by nbonato** [nbonato/spese#5]
Expenses should be displayed in order of date, rather than always appending the most recently added at the bottom.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the populateExpenseList function in expenseList.js to sort expenses by date in descending order (most recent first) before displaying them. This ensures that expenses are always displayed in order of date, rather than by the order they were added.

You can review changes in this commit: https://github.com/mnmnk43434/nbonato-spese-5/commit/30f4bac343460fe31f69101896aeca10aa4f878e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
